---
- name: Provision Web Servers
  hosts: all
  tasks:

    - name: Install pip3
      apt:
        update_cache: yes
        name: python3-pip
      become: yes

    - name: Install python docker sdk
      shell: |
        pip3 install docker
      become: yes

    - name: Install docker
      apt:
        name: docker.io
      become: yes

    - name: Start Docker
      shell: |
        systemctl start docker
        systemctl enable docker
      become: yes
    
    - name: Pull nginx docker
      shell: |
        docker run --name my-nginx -v /var/www/html:/usr/share/nginx/html:ro -d -p 9080:80 nginx
      become: yes
    
    - name: Copy files
      copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: 0644
      become: yes